language: elixir

os:
  - linux

elixir:
  - 1.10
  - 1.9
  - 1.8
  - 1.7
  - 1.6

otp_release:
  - 22.2
  - 19.3
  - 18.3

matrix:
  exclude:
    - elixir: 1.9
      otp_release: 19.3
    - elixir: 1.9
      otp_release: 18.3
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.8
      otp_release: 18.3
    - elixir: 1.7
      otp_release: 18.3
    - elixir: 1.6
      otp_release: 22.0
    - elixir: 1.6
      otp_release: 18.3

before_install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  - mix test --trace
